//cadastrar produtos

POST http://localhost:4002/products
content-type: application/json

{
    "name": "bola",
    "price": 4
}

###

//ver produtos cadastrados
GET http://localhost:4002/products/


//localixar pelo ID produtos
###
GET http://localhost:4002/products/5760e5ae-eb93-434e-b5a9-fd4d82458b0c

###

//Alterar produtos cadastrados pelo ID
PUT http://localhost:4002/products/f2c1b512-1162-4e4a-b739-caddb4988343
content-type: application/json

{
    "name": "apito rosa",
    "price": 1.00
}

//Deletar produto
###
DELETE http://localhost:4002/products/f2c1b512-1162-4e4a-b739-caddb4988343
